<?php
/*this file is a collection of functions that effect the
  portfolios table of the database. */

/*this function taks 5 parameters:
  -the title of the portfolio piece
  -the year the portfolio piece was created
  -the path to the thumbnail of the image
  -the path to the full image [optional]
  -the url where the portfolio piece is posted online [optional]
  The function then adds an entry to the portfolios table using the
  given parameters. If no thumbnail was generated by the upload form,
  an error is thrown.*/
function add_portfolio($title, $year, $thumb, $image, $url){
  global $db;
  if($thumb == ' '){
    return $no_thumb;
  }
  $query = "INSERT INTO portfolios (title, year, thumb, image, url)
            VALUES ('$title', $year, '$thumb', '$image', '$url')";
  $db->exec($query);
}

/*this function takes a portfolio id as a parameter. It finds the
  portfolio entry that matches the given id and deletes it from
  the database along with the saved images. */
function delete_portfolio($id){
  global $db;
  $query = "SELECT * FROM portfolios WHERE id = $id";
  $portfolio = $db->query($query);
  $portfolio = $portfolio->fetch();
  unlink($portfolio['image']);
  unlink($portfolio['thumb']);
  $query = "DELETE FROM portfolios WHERE id = $id";
  $portfolio = $db->exec($query);
}

/*this function shows all of the portfolio pieces that were created
  during the selected year.*/
function show_portfolio($year){
  global $db;
  $query = "SELECT * FROM portfolios WHERE year = $year";
  $portfolio = $db->query($query);
  return $portfolio;
}

/*this function gets the all of the years in which portfolio pieces
  were created. An array of these years is sorted and returned for display.*/
function get_years(){
  global $db;
  $query = "SELECT year FROM portfolios";
  $all_years = $db->query($query);
  
  $years = array();

  foreach ($all_years as $year){
    if (!in_array($year, $years)){
      $years[] = $year;
    }
  }

  rsort($years);

  return $years;
  
}


?>
